[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts=lib/chainlink-brownie-contracts/contracts"]
ffi = true
fs_permissions = [{ access = "read", path = "./broadcast" }]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# lib/chainlink-brownie-contracts/src/v0.8/shared/interfaces/AggregatorV3Interface.sol
# lib/chainlink-brownie-contracts/contracts/src/v0.8/shared/interfaces/AggregatorV3Interface.sol
# @chainlink/contracts/src/v0.8/shared/interfaces/AggregatorV3Interface.sol
# lib/chainlink-brownie-contracts/contracts/src/v0.8/shared/interfaces/AggregatorV3Interface.sol
